syntax = "proto3";

package job;

service Leader {
  rpc SubmitImage (JobRequest) returns (JobAccepted);
}

service Worker {
  rpc ExecuteJob (WorkerJob) returns (JobAccepted);
}

service Client {
  rpc DeliverImage (JobResult) returns (DeliveryAck);
}

message JobRequest {
  string job_id = 1;
  string filename = 2;
  bytes image_data = 3;
  string client_ip = 4;
  uint32 client_port = 5;
}

message WorkerJob {
  string job_id = 1;
  string filename = 2;
  bytes image_data = 3;
  string client_ip = 4;
  uint32 client_port = 5;
  string leader_ip = 6;
}

message JobAccepted {
  bool accepted = 1;
  string message = 2;
}

message JobResult {
  string job_id = 1;
  string filename = 2;
  bytes image_data = 3;
  string processed_by = 4;
}

message DeliveryAck {
  bool accepted = 1;
  string message = 2;
}
